# CONFIG UNICA – Pipeline semplice e deterministica per narrativa italiana
# Pipeline: Normalize → LanguageTool → LLM → LanguageTool

correction:
  pipeline: normalize_lt_llm_lt
  min_paragraph_length: 3            # includi dialoghi brevi (“Sì.”)
  abort_on_low_success: false        # non interrompere mai a metà
  chunk_max_tokens: 1800

openai:
  # imposta una temperatura molto bassa per correzioni deterministiche
  temperature: 0.0
  max_tokens: 1200

languagetool:
  server_url: http://localhost:8081
  timeout: 25
  language: it
  enabled_rules:
    - MORFOLOGIK_RULE_IT_IT
    - ITALIAN_SPELLCHECK
    - WRONG_APOSTROPHE
    - E_APOSTROPHE
    - WHITESPACE_RULE
    - COMMA_WHITESPACE
    - PERIOD_WHITESPACE
    - COLON_WHITESPACE
    - SEMICOLON_WHITESPACE
    - UPPERCASE_SENTENCE_START
    - REPEATED_WORDS
    - UNPAIRED_BRACKETS
  disabled_rules: []

glossary:
  words:
    - "Nuraxia"
    - "Youcanprint"
    - "Màrquez"
    - "Kiki"
