# Configurazione ottimizzata per LIBRI DI STORIA
# Modalità specifica per documenti storici con protezione nomi propri

correction:
  max_tokens_per_chunk: 2000   # Chunk più piccoli per maggiore precisione
  max_paragraphs_per_chunk: 3  # Meno paragrafi per controllo granulare
  mode: historical             # Nuova modalità specifica
  quality_threshold: 0.90      # Solo correzioni molto sicure
  safety_threshold: 0.87       # Protezione elevata per contenuto storico
  enable_backup: true
  enable_validation: true
  cache_enabled: true
  min_quality_threshold: 0.85  # Soglia minima alta per evitare correzioni dubbie
  batch_size: 15              # Batch piccoli per maggiore controllo
  min_success_rate: 0.80      # Alta aspettativa di successo
  min_paragraph_length: 10    # Standard
  max_workers: 2              # Meno parallelismo per maggiore precisione

# Configurazione specifica per testi storici
historical_protection:
  protect_proper_nouns: true           # Protegge nomi propri
  protect_historical_terms: true      # Protegge terminologia storica
  avoid_modernization: true           # Evita modernizzazione linguistica
  minimal_case_changes: true          # Evita modifiche maiuscole/minuscole eccessive
  preserve_archaic_forms: true        # Preserva forme linguistiche arcaiche
  
openai:
  model: gpt-4o-mini
  max_retries: 2              # Meno retry per fallire velocemente
  timeout: 60                 # Timeout più lungo per analisi accurata
  temperature: 0.1            # Molto deterministica per precisione
  rate_limit_buffer: 0.9      # Molto conservativa
  max_tokens_per_request: 6000 # Ridotto per chunk più piccoli
  
languagetool:
  server_url: "http://localhost:8081"
  timeout: 15                 # Timeout maggiore per analisi accurata
  language: "it"
  # Regole specifiche per testi storici
  enabled_rules:
    - "IT_ACCENTI"           # Solo accenti essenziali
    - "MORFOLOGIK_RULE_IT_IT" # Solo errori ortografici evidenti
  disabled_rules:
    - "UPPERCASE_SENTENCE_START"  # Evita modifiche di maiuscole
    - "E_APOSTROPHE"             # Evita correzioni apostrofi
    - "WRONG_APOSTROPHE"         # Evita correzioni apostrofi

# Glossario protetto per nomi storici
protected_terms:
  historical_names:
    - "Stefani"
    - "Vinicio" 
    - "Silvana"
    - "Dulia"
    - "Julia"
  
  historical_places:
    - "Roma"
    - "Gallia"
    - "Britannia"
    
  archaic_forms:
    - "nell'"
    - "dell'"
    - "l'"
    - "un'"

# Prompt specifico per modalità storica
correction_prompt_historical: |
  Sei un correttore specializzato in TESTI STORICI. 
  
  REGOLE FONDAMENTALI:
  1. NON modificare MAI nomi propri storici (persone, luoghi)
  2. NON modernizzare la lingua - preserva lo stile dell'epoca
  3. Correggi SOLO errori ortografici evidenti e grammaticali gravi
  4. NON cambiare maiuscole/minuscole se non strettamente necessario
  5. Preserva apostrofi e contrazioni esistenti
  6. NON "migliorare" il testo - correggi solo errori reali
  
  Concentrati solo su:
  - Errori di battitura evidenti
  - Errori grammaticali gravi
  - Punteggiatura chiaramente sbagliata
  
  EVITA:
  - Cambiare nomi di persone storiche
  - Modernizzare terminologia
  - Correzioni "estetiche"
  - Modifiche di stile

validation:
  max_length_change_percent: 5.0    # Massimo 5% di cambiamento
  min_confidence_score: 0.92        # Confidence molto alta
  backup_enabled: true
  check_duplicates: true
  check_truncation: true
