# CONFIGURAZIONE UNICA OTTIMIZZATA PER ITALIANO
# Sistema semplificato con un solo obiettivo: correggere BENE l'italiano

correction:
  # Parametri ottimizzati per risultati eccellenti in italiano
  mode: italian_optimized           # Modalità unica specializzata
  quality_threshold: 0.75          # Bilanciato: non troppo severo, non troppo permissivo
  safety_threshold: 0.70           # Sicurezza adeguata
  
  # NUOVA PIPELINE INVERTITA (AI → LanguageTool)
  pipeline_order: ai_first          # ai_first | languagetool_first (per rollback)
  languagetool_mode: quality_check  # primary | quality_check
  anti_regression: true             # Previene regressioni semantiche
  
  # Processamento ottimizzato
  max_tokens_per_chunk: 2000       # Chunk medi per buon bilanciamento
  max_paragraphs_per_chunk: 3      # 3 paragrafi per volta
  batch_size: 25                   # Batch medio per stabilità
  min_paragraph_length: 10         # Processa anche paragrafi corti
  
  # Abilita tutte le validazioni importanti
  enable_backup: true
  enable_validation: true
  cache_enabled: true              # Cache per velocità
  conservative_mode: false         # Non troppo conservativo
  
  # Lavoratori ottimizzati
  max_workers: 2                   # Due worker per stabilità

openai:
  # Configurazione AI ottimizzata per italiano
  model: gpt-5-mini-2025-08-07     # Modello più recente per maggiore precisione
  temperature: 0.1                 # Più deterministica per ridurre errori
  max_tokens: 3000                 # Adeguato per chunks medi
  timeout: 60                      # Tempo ragionevole
  max_retries: 3
  retry_delay: 2.0
  
  # Rate limiting conservativo per evitare problemi
  requests_per_minute: 45
  max_concurrent_requests: 2

languagetool:
  # LanguageTool configurato come QUALITY CHECKER (nuova pipeline)
  server_url: http://localhost:8081
  timeout: 20
  language: it
  
  # Modalità quality check: più conservativa e meno aggressiva
  quality_check_mode: true
  aggressive_corrections: false
  
  # REGOLE SPECIFICHE PER QUALITY CHECK - solo errori evidenti
  enabled_rules:
    # Solo errori ortografici evidenti
    - MORFOLOGIK_RULE_IT_IT         # Ortografia italiana (solo errori chiari)
    - WRONG_APOSTROPHE               # po' vs pò 
    
    # Punteggiatura essenziale
    - UPPERCASE_SENTENCE_START       # Maiuscole dopo punti
    - UNPAIRED_BRACKETS             # Parentesi non chiuse
    - MULTIPLE_EXCLAMATION_MARK     # !!! → !
    - MULTIPLE_QUESTION_MARK        # ??? → ?
    - REPEATED_WORDS                # parole parole duplicate
    
  # DISABILITA regole che possono creare regressioni semantiche
  disabled_rules:
    - ITALIAN_SPELLCHECK             # Troppo aggressivo, può correggere male
    - E_APOSTROPHE                   # Può interferire con correzioni AI
    - WHITESPACE_RULE               # AI gestisce meglio gli spazi
    - COMMA_WHITESPACE              # AI gestisce meglio la punteggiatura
    - PERIOD_WHITESPACE             # AI gestisce meglio la punteggiatura
    - PRON_GLI_E_L                  # AI gestisce meglio la grammatica
    - COMMA_PARENTHESIS_WHITESPACE  # Troppo rigida
    - TYPOGRAPHY                    # Può creare problemi
    
  # Parametri conservativi per quality check
  max_workers: 1                   # Single thread per evitare interferenze
  confidence_threshold: 0.9        # Solo correzioni molto sicure

validation:
  # Validazione bilanciata
  max_length_change_percent: 20.0  # Massimo 20% di cambio lunghezza
  min_confidence_score: 0.75       # Allineato con quality_threshold
  backup_enabled: true
  check_duplicates: true
  check_truncation: true

cache:
  # Cache ottimizzata
  enabled: true
  ttl_hours: 24                    # Cache giornaliera
  similarity_threshold: 0.90       # Alta similarità per cache hit
  quality_threshold: 0.75          # Allineato con configurazione
  auto_cleanup: true
  max_entries: 10000

parallel:
  # Parallelismo bilanciato
  enabled: true
  max_concurrent_workers: 2        # Due worker per stabilità
  rate_limit_per_minute: 45        # Allineato con OpenAI
  timeout_seconds: 120             # 2 minuti max per job

logging:
  # Logging essenziale
  level: INFO
  format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  date_format: "%H:%M:%S"
  file_enabled: true
  file_path: "logs/correzione_italiana.log"

# Configurazione prompts specifici per italiano
italian_prompts:
  main_instruction: |
    Sei un esperto correttore di bozze per la lingua italiana.
    Correggi SOLO errori evidenti di:
    1. Ortografia (parole scritte male)
    2. Grammatica (verbi, accordi, ecc.)
    3. Punteggiatura (virgole, punti, ecc.)
    4. Apostrofi (po' invece di pò, ecc.)
    5. Maiuscole/minuscole (dopo punti, nomi propri)
    6. Spazi mancanti o doppi
    
    NON modificare:
    - Lo stile dell'autore
    - Il registro linguistico
    - Il contenuto o il significato
    - Le scelte stilistiche volontarie
    
    Mantieni il testo il più possibile fedele all'originale.

  context_preservation: |
    Mantieni sempre il significato originale del testo.
    Se non sei sicuro al 100% di una correzione, non farla.
    
  quality_check: |
    Verifica che ogni correzione sia:
    - Grammaticalmente corretta in italiano
    - Appropriata al contesto
    - Necessaria (non solo stilistica)

# Configurazione pipeline invertita (AI → LanguageTool)
pipeline_config:
  description: "Pipeline invertita per migliorare correzioni semantiche"
  
  ai_first_stage:
    description: "AI agisce per prima per correzioni semantiche intelligenti"
    focus:
      - "Correzioni semantiche (vlta → volta, bottaga → bottega)"
      - "Comprensione contestuale (C'era una volta)"
      - "Errori evidenti (U giorno → Un giorno)"
      - "Maiuscole (alfredo → Alfredo)"
    
  languagetool_quality_check:
    description: "LanguageTool come controllo qualità finale"
    focus:
      - "Solo errori ortografici evidenti non corretti dall'AI"
      - "Punteggiatura mancante"
      - "Parentesi non chiuse"
      - "Maiuscole dopo punti"
    anti_regression:
      - "Non correggere se introduce errori semantici"
      - "Non modificare correzioni già fatte dall'AI"
      - "Mantenere il contesto semantico preservato dall'AI"
